Algoritmo "soma_numeros"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/06/2024
funcao Soma (a, b: inteiro): inteiro

inicio
  retorne a + b
fimfuncao

Var
// Seção de Declarações das variáveis
 num1, num2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 num1 <- 3
 num2 <- 4
   escreval ("A soma de ", num1, " e ", num2, " é: ", Soma(num1,num2))

Fimalgoritmo