Algoritmo "Função dobro do numero"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/06/2024
funcao Dobro (n: inteiro): inteiro

inicio
  retorne n * 2
fimfuncao

Var
// Seção de Declarações das variáveis 
  numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  numero <- 5
  
  escreval ("O dobro de ", numero, " é : ", Dobro(numero))

Fimalgoritmo