Algoritmo "Função_RetornarInteiro"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/06/2024
Var
// Seção de Declarações das variáveis 
valor : inteiro
funcao retornarinteiro : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  retorne 15
fimfuncao

inicio


valor <- retornarinteiro

escreval ("O valor é: ", valor)
Fimalgoritmo